Update README.md
deavmi/HaikuDocs pull request #1
Opened 2017-05-18 22:19 UTC by clasqm

Minor language edit

2017-05-19 15:48 UTC, deavmi commented
Is there a reason for ignoring all files that end in `.html`?

2017-05-19 16:03 UTC, deavmi requested changes
* Undo the changes of the .gitignore unless there is a good reason for this.
* In the README add a `a` after the "Why not just write [here] "
* We do not need 2 extra lines after the end of the `README.md` in the root of the repo.
* Remove the License info from the document.
* Or the markdown editor you used.

Make these changes, I will do a final check and then everything should be fine for a merge.

2017-05-19 16:43 UTC, deavmi commented on README.md
> +
Remove this.

2017-05-19 17:11 UTC, deavmi commented
See if you can style the page like this too: https://github.com/deavmi/HaikuDocs/blob/en/TEMPLATE.md

2017-05-19 19:24 UTC, clasqm commented
OK, I see where you are going with this.

_in the README add a a after the "Why not just write [here] "_

If that's the way you want it, but it is grammatically incorrect. "Documentation" is not a countable noun, you don't say "one documentation, two documentations".

I've deleted the gitignore. That was just to stop committing the htmls I generate to see what the final product looks like, in case I forgot to delete them on my offline branch. But I see now that that would then end up in the whole project. Sorry, I'll just have to be careful.

_We do not need 2 extra lines after the end of the README.md in the root of the repo._
done
_Remove the License info from the document._
done
_Or the markdown editor you used._
done

OK, that should help me in future contributions, now that I know what you would like to see here. The two of us may just be the entire South African Haiku Users Group, so we must stick together! ;-)

2017-05-20 14:12 UTC, deavmi commented
Gonna merge soon tonight. Just wrote NBTs early this morning so I need some sleep. Thanks for the great work!

2017-05-20 14:21 UTC, deavmi commented
Oh you can remove the `a` then again. Sorry about that grammar mistake.

2017-05-20 14:36 UTC, deavmi commented
Try style it according yo CONTRIBUTING.md

2017-05-20 15:28 UTC, deavmi approved these changes

2017-05-20 15:29 UTC, deavmi commented
Actually all is fine.

2017-05-20 15:30 UTC, merged

2017-05-21 14:19 UTC, deavmi commented
We must definately stick toghether. The Haiku User Group in ZA is small. I really think this project can be successful as it is on GitHub and it is a platform that makes contributing really easy. Also Markdown is a great markup language to be doing this type of project in.

This is a side project of mine but when I am not busy with other work I will definately be working on this.

2017-05-21 15:43 UTC, clasqm commented
I'm finding that I spend half an hour writing documentation, and a whole day fighting with GitHub. So my time will be better spent if I write up everything I want to add and then give it another shot. See you in a week or two.

> On 21 May 2017, at 4:19 PM, Tristan B. Kildaire <notifications@github.com> wrote:
> 
> We must definately stick toghether. The Haiku User Group in ZA is small. I really think this project can be successful as it is on GitHub and it is a platform that makes contributing really easy. Also Markdown is a great markup language to be doing this type of project in.
> 
> This is a side project of mine but when I am not busy with other work I will definately be working on this.
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub <https://github.com/deavmi/HaikuDocs/pull/1#issuecomment-302939605>, or mute the thread <https://github.com/notifications/unsubscribe-auth/AX5fRgEsh-n0tT2u7hnbjK5vwd2r85h3ks5r8EfngaJpZM4Nf3UH>.
>

2017-05-21 21:12 UTC, deavmi commented
Thanks for the hard work and contiued hard work sir. I appreciate it. I will be busy with exams in those weeks but that's fine. I can then review the changes/additions in my spare time (which I know I will have - it's matric (not hell)).

2017-05-21 21:14 UTC, deavmi commented
Also, sounds like a good plan to just write a whole chunk of documents and then commit and push them so that we basically have a day to review the changes and make tweaks if need be so.

Your first contribution worked out just like that; it was __stellar__ .

2017-05-21 21:15 UTC, deavmi commented
Also, if you could just do this file move please, https://github.com/deavmi/HaikuDocs/issues/4, that would be great ;).

2017-05-21 21:36 UTC, deavmi commented
One more thing. Don't add images to your next commit (do take screenshots) and add the image markdown code for where the image is to be but don't upload them. I want to investigate image hosting so that this repo doesn't become too large.

2017-05-22 12:29 UTC, clasqm commented
I deleted that branch after you merged. Now I need to resync my main branch
to yours before I can do anything else but WTH is the button for that? I am
starting to hate Github.

On Sun, May 21, 2017 at 11:15 PM, Tristan B. Kildaire <
notifications@github.com> wrote:

> Also, if you could just do this file move please, #4
> <https://github.com/deavmi/HaikuDocs/issues/4>, that would be great ;).
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/deavmi/HaikuDocs/pull/1#issuecomment-302963806>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AX5fRhsnB4jSZY06z_RpsjCigZe_ghKrks5r8KmPgaJpZM4Nf3UH>
> .
>

2017-05-23 05:01 UTC, deavmi commented
Have you cloned the repo using `git`?

Make a backup first just incase.

If so then surely you can `git pull`?

2017-05-23 05:03 UTC, deavmi commented
Tell me how that goes then we can see what to do next.

2017-05-23 05:05 UTC, deavmi commented
Seeing that you were working in a seperate branch then updating the main branch should be as easy as `git pull` then you can make a new branch off of that? And put your changes into there and commit and push that to your repo and make a PR to merge from that branch to the `en` branch in my repo.

2017-05-23 05:07 UTC, deavmi commented
GitHub is alright but it is only a frontend (only good feature - not that it is mandatory - is PRs).

You using `git` on the command-line?